const bikes = [
  {
    bikeName: "ETM XL",
    imagePath:
      "https://stat.overdrive.in/wp-content/odgallery/2022/08/63809_2022_Royal_Enfield_Hunter_350_468x263.jpg",
    frame: "Q345b_6061 Forge Aluminum Alloy",
    product_weight: "258Lbs",
    wheelbase: "1424mm [56 Inch]",
    seat: "Foam Padded",
    assembly_time: "1 hour",
    throttle: "Hall Sensor Variable MX Throttle",
    controller: "TruMoto Noisy Cricket",
    motor: "BLDC with/ 0-1-2-3-4 Transmission",
    suspension: "Single-chamber Dual-Adjustable",
    driven_chain: "520",
    brakes: "Front and Rear Disk [modeled after Brembo]",
    tires: "Cordial Front & Rear 80/100-21; 110/90-18",
    battery_pack: "72v 60ah",
    battery_life: "Up to 50 miles",
    charging_time: "1-6 Hours [10Amp charger]",
    charger: "10 Amp",
    display: "LCD Display",
    lights: "All LED",
    accessories_material:
      "Steering, Brake & Clutch Lever Aluminium are 7075 Aluminium",
  },
  {
    bikeName: "KTM",
    imagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzIjMjqANtd00Ax_7WmK3qVEhKGaxsq4b5Ktum2L_DDA&s",
    frame: "Ground Clearance - 13 inches",
    product_weight: "115 Lbs",
    wheelbase: "41 Inches",
    seat: "Foam Padded",
    assembly_time: "1 hour",
    throttle: "Hall Sensor Variable MX Throttle",
    controller: "TruMoto Little Bit",
    motor: "Brushless [7000 + RPM]",
    suspension: "Hydraulic Front Forks",
    final_drive: "1OT/7OT, T8F Chain",
    brakes: "Front and Rear Hydraulic Disk Brakes",
    tires: "2.75x14 MX Knobby; 3.00x12 MX Knobby",
    battery_pack: "60v 20ah",
    battery_life: "3 Hours",
    charging_time: "4-6 Hours",
    charger: "Charger Included, Fast Charge Ready",
    battery_meter: "Handlebar Mounted Voltage Gauge",
    recommended_age: "9+",
  },
  {
    bikeName: "ETM MINI",
    imagePath:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYCZUvOCDK39zMcXqt8PX4n1Vx1em2QBhXVqvfcwbcDg&s",
    frame: "Ground Clearance - 10.5 inches",
    product_weight: "95Lbs",
    wheelbase: "38 Inches",
    seat: "Foam Padded",
    assembly_required: "Yes",
    assembly_time: "1 hour",
    throttle: "Hall Sensor Variable MX Throttle",
    controller: "TruMoto Noisy Cricket",
    motor: "Brushless (7000 + RPM)",
    suspension: "Hydraulic Front Forks",
    final_drive: "1OT/76T, 219H# Chain",
    brakes: "Front and Rear Hydraulic Disk Brakes",
    tires: "2.75x12 MX Knobby; 3.00x10 MX Knobby",
    recommended_age: "6+",
    battery_pack: "72 Volt 20Ah Li-Ion",
    power_modes: "Eco, Sport, Warp Drive",
    battery_life: "1-4 Hours",
    charging_time: "4-6 Hours",
    charger_included: "Yes",
    display: "LCD Display",
    battery_meter: "Handlebar Mounted Voltage Gauge",
  },
];

export default bikes;
